--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/shikikan/wallpaper/86141827_p0.jpg"

-- Special
background="#181611"
foreground="#f1ecdf"
cursor="#f1ecdf"

-- Colors
color0="#181611"
color1="#A99169"
color2="#D2A26B"
color3="#D8C266"
color4="#B0A391"
color5="#D4B397"
color6="#EBD4A9"
color7="#f1ecdf"
color8="#a8a59c"
color9="#A99169"
color10="#D2A26B"
color11="#D8C266"
color12="#B0A391"
color13="#D4B397"
color14="#EBD4A9"
color15="#f1ecdf"
