# Shell variables
# Generated by 'wal'
wallpaper="/home/shikikan/wallpaper/86141827_p0.jpg"

# Special
background='#181611'
foreground='#f1ecdf'
cursor='#f1ecdf'

# Colors
color0='#181611'
color1='#A99169'
color2='#D2A26B'
color3='#D8C266'
color4='#B0A391'
color5='#D4B397'
color6='#EBD4A9'
color7='#f1ecdf'
color8='#a8a59c'
color9='#A99169'
color10='#D2A26B'
color11='#D8C266'
color12='#B0A391'
color13='#D4B397'
color14='#EBD4A9'
color15='#f1ecdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
