# Shell variables
# Generated by 'wal'
wallpaper="/home/shikikan/wallpaper/cat.jpg"

# Special
background='#2d241e'
foreground='#f4efde'
cursor='#f4efde'

# Colors
color0='#2d241e'
color1='#8A6F8F'
color2='#B4A291'
color3='#D7B292'
color4='#EFD9A4'
color5='#EED5AE'
color6='#E9D8CC'
color7='#f4efde'
color8='#aaa79b'
color9='#8A6F8F'
color10='#B4A291'
color11='#D7B292'
color12='#EFD9A4'
color13='#EED5AE'
color14='#E9D8CC'
color15='#f4efde'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
