--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/shikikan/wallpaper/cat.jpg"

-- Special
background="#2d241e"
foreground="#f4efde"
cursor="#f4efde"

-- Colors
color0="#2d241e"
color1="#8A6F8F"
color2="#B4A291"
color3="#D7B292"
color4="#EFD9A4"
color5="#EED5AE"
color6="#E9D8CC"
color7="#f4efde"
color8="#aaa79b"
color9="#8A6F8F"
color10="#B4A291"
color11="#D7B292"
color12="#EFD9A4"
color13="#EED5AE"
color14="#E9D8CC"
color15="#f4efde"
