#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color \#EFD9A4
bspc config normal_border_color \#D7B292


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 42
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# $HOME/.screenlayout/layout.sh &
xrandr -s 1360x768 &
nitrogen --restore &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
picom &
$HOME/.config/polybar/launch.sh &
killall  dunst &
dunst &
#lxpolkit &
